services:

    EasyAdmin\Application\ConfigFileToHtml:
        class: EasyAdmin\Application\ConfigFileToHtml
        arguments:
            - '@EasyAdmin\Parser\Xml\XmlParser'
            - '@EasyAdmin\Viewer\Html\FormType\FormViewer'
            - '@EasyAdmin\Application\FormTagFactory'

    EasyAdmin\Application\FormTagFactory:
        class: EasyAdmin\Application\FormTagFactory
