services:

    EasyAdmin\Application\ConfigFileToHtml:
        class: EasyAdmin\Application\ConfigFileToHtml
        arguments:
            - '@EasyAdmin\Parser\Xml\XmlParser'
            - '@EasyAdmin\Viewer\HtmlViewer'
