services:

    EasyAdmin\Application\ConfigFileToHtml:
        class: EasyAdmin\Application\ConfigFileToHtml
        arguments:
            - '@EasyAdmin\Application\Loader\ConfigurationLoader'
            - '@EasyAdmin\Parser\Xml\XmlParser'
            - '@EasyAdmin\Viewer\Html\FormType\FormViewer'
            - '@EasyAdmin\Domain\Form\FormType\FormFactory'

    EasyAdmin\Application\FormTagFactory:
        class: EasyAdmin\Application\FormTagFactory

    EasyAdmin\Application\Loader\ConfigurationLoader:
        class: EasyAdmin\Application\Loader\ConfigurationLoader
