services:

    EasyAdmin\I18N\Translator:
        class: EasyAdmin\I18N\Translator
        arguments:
            - '@EasyAdmin\I18N\I18nLoader'

    EasyAdmin\I18N\I18nLoader:
        class: EasyAdmin\I18N\I18nLoader
