services:

    EasyAdmin\Domain\Database\Connector: '@EasyAdmin\Infrastructure\Database\MySql\MysqlConnector'

    EasyAdmin\Domain\Database\ItemRepository: '@EasyAdmin\Infrastructure\Database\MySql\ItemRepository'
