services:

    EasyAdmin\Domain\DisplayList\FieldsParser:
        class: EasyAdmin\Domain\DisplayList\FieldsParser

    EasyAdmin\Domain\DisplayList\DisplayItemsParser:
        class: EasyAdmin\Domain\DisplayList\DisplayItemsParser
        arguments:
            - '@EasyAdmin\Domain\DisplayList\FieldsParser'
            - '@EasyAdmin\Infrastructure\Helper\Convertor\StringToIntegerConvertor'
