services:

    EasyAdmin\Domain\Form\FormType\FormFactory:
        class: EasyAdmin\Domain\Form\FormType\FormFactory
        arguments:
            - '@EasyAdmin\Application\FormTagFactory'
            - '@EasyAdmin\Domain\I18N\Translator'
