services:

    EasyAdmin\Application\Controller\CreateController:
        class: EasyAdmin\Application\Controller\CreateController
        arguments:
            - '@EasyAdmin\Application\Loader\ConfigurationLoader'
            - '@EasyAdmin\Domain\Parser\Parser'
            - '@EasyAdmin\Infrastructure\Viewer\Html\FormType\FormViewer'
            - '@EasyAdmin\Domain\Form\FormType\FormFactory'
            - '@EasyAdmin\Domain\Database\ItemRepository'
            - '@EasyAdmin\Domain\Message\FlashMessageFactory'
            - '@EasyAdmin\Infrastructure\Viewer\Html\Message\FlashMessageViewer'
