services:

    ##########
    # CREATE #
    ##########
    EasyAdmin\Application\Controller\Create\CreateController:
        class: EasyAdmin\Application\Controller\Create\CreateController
        arguments:
            - '@EasyAdmin\Application\Controller\Create\ItemStructureFactory'
            - '@EasyAdmin\Application\Controller\Create\ItemCreator'
            - '@EasyAdmin\Application\Controller\Create\ItemStructureViewer'

    EasyAdmin\Application\Controller\Create\ItemCreator:
        class: EasyAdmin\Application\Controller\Create\ItemCreator
        arguments:
            - '@EasyAdmin\Domain\Database\ItemRepository'
            - '@EasyAdmin\Domain\Message\FlashMessageFactory'
            - '@EasyAdmin\Infrastructure\Viewer\Html\Message\FlashMessageViewer'

    EasyAdmin\Application\Controller\Create\ItemStructureFactory:
        class: EasyAdmin\Application\Controller\Create\ItemStructureFactory
        arguments:
            - '@EasyAdmin\Application\Loader\ConfigurationLoader'
            - '@EasyAdmin\Domain\Parser\Parser'

    EasyAdmin\Application\Controller\Create\ItemStructureViewer:
        class: EasyAdmin\Application\Controller\Create\ItemStructureViewer
        arguments:
            - '@EasyAdmin\Infrastructure\Viewer\Html\FormType\FormViewer'
            - '@EasyAdmin\Domain\Form\FormType\FormFactory'

    ##########
    # UPDATE #
    ##########
    EasyAdmin\Application\Controller\Update\UpdateController:
        class: EasyAdmin\Application\Controller\Update\UpdateController
        arguments:
            - '@EasyAdmin\Application\Controller\Update\ItemStructureFactory'
            - '@EasyAdmin\Application\Controller\Update\ItemUpdator'
            - '@EasyAdmin\Application\Controller\Update\ItemStructureViewer'

    EasyAdmin\Application\Controller\Update\ItemStructureFactory:
        class: EasyAdmin\Application\Controller\Update\ItemStructureFactory
        arguments:
            - '@EasyAdmin\Application\Loader\ConfigurationLoader'
            - '@EasyAdmin\Domain\Parser\Parser'
            - '@EasyAdmin\Domain\Database\ItemRepository'

    EasyAdmin\Application\Controller\Update\ItemUpdator:
        class: EasyAdmin\Application\Controller\Update\ItemUpdator
        arguments:
            - '@EasyAdmin\Domain\Database\ItemRepository'
            - '@EasyAdmin\Domain\Message\FlashMessageFactory'
            - '@EasyAdmin\Infrastructure\Viewer\Html\Message\FlashMessageViewer'

    EasyAdmin\Application\Controller\Update\ItemStructureViewer:
        class: EasyAdmin\Application\Controller\Update\ItemStructureViewer
        arguments:
            - '@EasyAdmin\Infrastructure\Viewer\Html\FormType\FormViewer'
            - '@EasyAdmin\Domain\Form\FormType\FormFactory'

    ##########
    #  LIST  #
    ##########
    EasyAdmin\Application\Controller\DisplayList\ListController:
        class: EasyAdmin\Application\Controller\DisplayList\ListController
        arguments:
            - '@EasyAdmin\Application\Controller\DisplayList\ItemStructureFactory'
            - '@EasyAdmin\Domain\Database\ItemRepository'
            - '@EasyAdmin\Domain\DisplayList\DisplayItemsParser'

    EasyAdmin\Application\Controller\DisplayList\ItemStructureFactory:
        class: EasyAdmin\Application\Controller\DisplayList\ItemStructureFactory
        arguments:
            - '@EasyAdmin\Application\Loader\ConfigurationLoader'
            - '@EasyAdmin\Domain\Parser\Parser'
