imports:
    - { resource: controller.yaml }
    - { resource: loader.yaml }
    - { resource: logger.yaml }

services:

    EasyAdmin\Application\Router:
        class: EasyAdmin\Application\Router
        arguments:
            -
                - '@EasyAdmin\Application\Controller\Create\CreateController'
            - '@Symfony\Component\HttpFoundation\Request'

    EasyAdmin\Application\FormTagFactory:
        class: EasyAdmin\Application\FormTagFactory
