services:

    EasyAdmin\Application\Router:
        class: EasyAdmin\Application\Router
        arguments:
            -
                - '@EasyAdmin\Application\Controller\Create\CreateController'
                - '@EasyAdmin\Application\Controller\Update\UpdateController'
                - '@EasyAdmin\Application\Controller\DisplayList\ListController'
                - '@EasyAdmin\Application\Controller\Remove\RemoveController'
                - '@EasyAdmin\Application\Controller\Api\Values\ValuesController'
            - '@Symfony\Component\HttpFoundation\Request'
